services:
  - type: web
    name: habitnest-server
    runtime: node
    buildCommand: cd server && npm install && npm install --save-dev @types/node @types/express @types/cors @types/mongoose @types/bcryptjs @types/jsonwebtoken @types/express-validator && npm install express-validator@7.0.1 && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production 